import groovy.xml.MarkupBuilder

plugins {
    id 'com.android.application'
}

def twaManifest = [
    applicationId: 'app.lovable.cosmic_chronicle_gleam.twa',
    hostName: 'cosmic-chronicle-gleam.lovable.app',
    launchUrl: '/',
    name: 'Divya Panchang 1926-2126 | दिव्य पंचांग',
    launcherName: 'DIVYAPANCH',
    themeColor: '#F4B41A',
    themeColorDark: '#000000',
    navigationColor: '#000000',
    navigationColorDark: '#000000',
    navigationDividerColor: '#000000',
    navigationDividerColorDark: '#000000',
    backgroundColor: '#2A1035',
    enableNotifications: true,
    shortcuts: [],
    splashScreenFadeOutDuration: 300,
    generatorApp: 'bubblewrap-cli',
    fallbackType: 'customtabs',
    enableSiteSettingsShortcut: 'true',
    orientation: 'portrait',
]

android {
    compileSdkVersion 36
    namespace "app.lovable.cosmic_chronicle_gleam.twa"

    defaultConfig {
        applicationId "app.lovable.cosmic_chronicle_gleam.twa"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 3
        versionName "3"
        resValue "string", "appName", twaManifest.name
        resValue "string", "launcherName", twaManifest.launcherName
        def launchUrl = "https://" + twaManifest.hostName + twaManifest.launchUrl
        resValue "string", "launchUrl", launchUrl
        resValue "string", "webManifestUrl", 'https://cosmic-chronicle-gleam.lovable.app/manifest.webmanifest'
        resValue "string", "fullScopeUrl", 'https://cosmic-chronicle-gleam.lovable.app/'
        resValue "string", "hostName", twaManifest.hostName
        resValue "color", "colorPrimary", twaManifest.themeColor
        resValue "color", "colorPrimaryDark", twaManifest.themeColorDark
        resValue "color", "navigationColor", twaManifest.navigationColor
        resValue "color", "navigationColorDark", twaManifest.navigationColorDark
        resValue "color", "navigationDividerColor", twaManifest.navigationDividerColor
        resValue "color", "navigationDividerColorDark", twaManifest.navigationDividerColorDark
        resValue "color", "backgroundColor", twaManifest.backgroundColor
        resValue "string", "providerAuthority", twaManifest.applicationId + '.fileprovider'
        resValue "bool", "enableNotification", twaManifest.enableNotifications.toString()
        resValue "integer", "splashScreenFadeOutDuration", twaManifest.splashScreenFadeOutDuration.toString()
        resValue "string", "generatorApp", twaManifest.generatorApp
        resValue "string", "fallbackType", twaManifest.fallbackType
        resValue "bool", "enableSiteSettingsShortcut", twaManifest.enableSiteSettingsShortcut
        resValue "string", "orientation", twaManifest.orientation
    }

    signingConfigs {
        release {
            def ks = System.getenv('KEYSTORE_FILE')
            if (ks) {
                storeFile file(ks)
                storePassword System.getenv('KEYSTORE_PASSWORD')
                keyAlias 'ABCJUNGLE'
                keyPassword System.getenv('KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
    }
}

task generateShorcutsFile {
    def shortcutsFile = new File("$projectDir/src/main/res/xml", "shortcuts.xml")
    if (!shortcutsFile.parentFile.exists()) shortcutsFile.parentFile.mkdirs()
    def xmlWriter = new StringWriter()
    def xmlMarkup = new MarkupBuilder(new IndentPrinter(xmlWriter, "    ", true))
    xmlMarkup.'shortcuts'('xmlns:android': 'http://schemas.android.com/apk/res/android') {}
    shortcutsFile.text = xmlWriter.toString() + '\n'
}

preBuild.dependsOn(generateShorcutsFile)

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
}
