/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChoghadiyaRouteImport } from './routes/choghadiya'
import { Route as KundliRouteImport } from './routes/kundli'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as YearIndexRouteImport } from './routes/year.index'
import { Route as YearYearRouteImport } from './routes/year.$year'
import { Route as CalendarYearMonthRouteImport } from './routes/calendar.$year.$month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoghadiyaRoute = ChoghadiyaRouteImport.update({
  id: '/choghadiya',
  path: '/choghadiya',
  getParentRoute: () => rootRouteImport,
} as any)
const KundliRoute = KundliRouteImport.update({
  id: '/kundli',
  path: '/kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const YearIndexRoute = YearIndexRouteImport.update({
  id: '/year/',
  path: '/year/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearYearRoute = YearYearRouteImport.update({
  id: '/year/$year',
  path: '/year/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarYearMonthRoute = CalendarYearMonthRouteImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choghadiya': typeof ChoghadiyaRoute
  '/kundli': typeof KundliRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/day/$date': typeof DayDateRoute
  '/year/$year': typeof YearYearRoute
  '/calendar/': typeof CalendarIndexRoute
  '/year/': typeof YearIndexRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choghadiya': typeof ChoghadiyaRoute
  '/kundli': typeof KundliRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/day/$date': typeof DayDateRoute
  '/year/$year': typeof YearYearRoute
  '/calendar': typeof CalendarIndexRoute
  '/year': typeof YearIndexRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choghadiya': typeof ChoghadiyaRoute
  '/kundli': typeof KundliRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/day/$date': typeof DayDateRoute
  '/year/$year': typeof YearYearRoute
  '/calendar/': typeof CalendarIndexRoute
  '/year/': typeof YearIndexRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/choghadiya'
    | '/kundli'
    | '/privacy'
    | '/search'
    | '/day/$date'
    | '/year/$year'
    | '/calendar/'
    | '/year/'
    | '/calendar/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/choghadiya'
    | '/kundli'
    | '/privacy'
    | '/search'
    | '/day/$date'
    | '/year/$year'
    | '/calendar'
    | '/year'
    | '/calendar/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/choghadiya'
    | '/kundli'
    | '/privacy'
    | '/search'
    | '/day/$date'
    | '/year/$year'
    | '/calendar/'
    | '/year/'
    | '/calendar/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChoghadiyaRoute: typeof ChoghadiyaRoute
  KundliRoute: typeof KundliRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  DayDateRoute: typeof DayDateRoute
  YearYearRoute: typeof YearYearRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  YearIndexRoute: typeof YearIndexRoute
  CalendarYearMonthRoute: typeof CalendarYearMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choghadiya': {
      id: '/choghadiya'
      path: '/choghadiya'
      fullPath: '/choghadiya'
      preLoaderRoute: typeof ChoghadiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundli': {
      id: '/kundli'
      path: '/kundli'
      fullPath: '/kundli'
      preLoaderRoute: typeof KundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/': {
      id: '/year/'
      path: '/year'
      fullPath: '/year/'
      preLoaderRoute: typeof YearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/$year': {
      id: '/year/$year'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof YearYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$year/$month': {
      id: '/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof CalendarYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChoghadiyaRoute: ChoghadiyaRoute,
  KundliRoute: KundliRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  DayDateRoute: DayDateRoute,
  YearYearRoute: YearYearRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  YearIndexRoute: YearIndexRoute,
  CalendarYearMonthRoute: CalendarYearMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
